### ISSUE TITLE
map->odom tf publish doesn't meet expected update_time

### ISSUE THREAD

**Issue by HappySamuel** [neobotix/neo_localization2#8]
Hi

I tried neo_localization2 in gazebo simulation, but i couldn't have it to provide `map->odom` transform at 10Hz rate (100ms). Any idea / hints for how to achieve it?

Here's the rate of topics provided to neo_localization2 node:
`/scan` at 20Hz
`odom->base_footprint` at 40Hz

Besides, there's a need to update parameter name in provided test_setup.yaml 
Change
 `loc_update_rate: 10`   #Used in ROS1 neo_localization
to
 `loc_update_time: 100`  #Used in ROS2 neo_localization2

Best,
Samuel

**Comment by padhupradheep** [comment]
Hey, it is really strange. The update you had given beneath will help you achieve 10 Hz. 

Thanks for the update though.

**Comment by HappySamuel** [comment]
Hi @padhupradheep 

Maybe i show you my current parameters setting, then you will have idea where i did wrongly.
```
neo_localization2:
  ros__parameters:
    map_frame: map
    odom_frame: odom
    base_frame: base_footprint

    # exponential low pass gain for localization update (0 to 1)
    #   (higher gain means odometry is less used / relied on)
    update_gain: 0.5

    # time based confidence gain when in 2D / 1D mode
    confidence_gain: 0.01

    # how many particles (samples) to spread (per update)
    sample_rate: 10

    # localization update rate [1/s] / localization update time [ms]
#    loc_update_rate: 10
    loc_update_time: 100

    # map tile update rate [1/s]
    map_update_rate: 0.5

    # map tile size in pixels
    map_size: 1000

    # how often to downscale (half) the original map
    map_downscale: 0

    # how many 3x3 gaussian smoothing iterations are applied to the map
    num_smooth: 5

    # minimum score for valid localization (otherwise 0D mode)
    #    higher values make it go into 0D mode earlier
    min_score: 0.2

    # odometry error in x and y [m/m] [1]
    #    how fast to increase particle spread when in 1D / 0D mode
    odometry_std_xy: 0.01

    # odometry error in yaw angle [rad/rad] [1]
    #    how fast to increase particle spread when in 0D mode
    odometry_std_yaw: 0.01

    # minimum particle spread in x and y [m]
    min_sample_std_xy: 0.025

    # minimum particle spread in yaw angle [rad]
    min_sample_std_yaw: 0.025

    # initial/maximum particle spread in x and y [m]
    max_sample_std_xy: 0.5

    # initial/maximum particle spread in yaw angle [rad]
    max_sample_std_yaw: 0.5

    # threshold for 1D / 2D position decision making (minimum average second order gradient)
    #   if worst gradient direction is below this value we go into 1D mode
    #   if both gradient directions are below we may go into 0D mode, depending on disable_threshold
    #   higher values will make it go into 1D / 0D mode earlier
    constrain_threshold: 0.1

    # threshold for 1D / 2D decision making (with or without orientation)
    #   higher values will make it go into 1D mode earlier
    constrain_threshold_yaw: 0.2

    # minimum number of points per update
    min_points: 20

    # solver update gain, lower gain = more stability / slower convergence
    solver_gain: 0.1

    # solver update damping, higher damping = more stability / slower convergence
    solver_damping: 1000.0

    # number of gauss-newton iterations per sample per scan
    solver_iterations: 20

    # maximum wait for getting transforms [s]
    transform_timeout: 0.2

    # if to broadcast map frame
    broadcast_tf: true
```
Note: The LaserScan `/scan` has 2000 points / revolute


Best,
Samuel
